CREATE OR REPLACE FUNCTION CREAR_SALA(VARCHAR) RETURNS BOOLEAN AS $$
DECLARE
	CONTAR INTEGER;
BEGIN	
	CONTAR := COUNT(NOMBRESALA) FROM SALA WHERE SALA.NOMBRESALA = $1;

	IF CONTAR = 0 THEN
		INSERT INTO SALA(NOMBRESALA) VALUES ($1);
		RETURN TRUE;
	ELSE
		RETURN FALSE;
	END IF;
END;
$$ LANGUAGE PLPGSQL;


CREATE OR REPLACE FUNCTION CREAR_USUARIO(VARCHAR) RETURNS BOOLEAN AS $$
DECLARE
	CONTAR INTEGER;
BEGIN	
	CONTAR := COUNT(NOMBREUSUARIO) FROM USUARIO WHERE USUARIO.NOMBREUSUARIO = $1;

	IF CONTAR = 0 THEN
		INSERT INTO USUARIO(NOMBREUSUARIO) VALUES ($1);
		RETURN TRUE;
	ELSE
		RETURN FALSE;
	END IF;
END;
$$ LANGUAGE PLPGSQL;


CREATE OR REPLACE FUNCTION TODAS_SALAS() RETURNS REFCURSOR AS $$
DECLARE
	MYCURS REFCURSOR;
BEGIN
	OPEN MYCURS FOR SELECT * FROM SALA ORDER BY ID;
	RETURN MYCURS;
END;
$$ LANGUAGE PLPGSQL;


